import React, { useState, useMemo } from 'react';
import { Box, Paper, Typography, Grid, Button, Chip, IconButton } from '@mui/material';
import {
  DescriptionOutlined as DocIcon,
  LocalShippingOutlined as DispatchIcon,
  Inventory2Outlined as GRNIcon,
  ReceiptOutlined as InvoiceIcon,
  AccountBalanceWalletOutlined as SettlementIcon,
  AccountBalanceOutlined as BankIcon,
  CheckCircle as CheckIcon,
  Warning as WarningIcon,
  Error as ErrorIcon,
  HelpOutline as MissingIcon,
  AutoAwesome as AIIcon,
  FileDownloadOutlined as DownloadIcon
} from '@mui/icons-material';

// --- Types & Mock Data ---

type NodeStatus = 'Matched' | 'Partial' | 'Missing' | 'Conflict';
type NodeType = 'Purchase Order' | 'Dispatch' | 'GRN' | 'Invoice' | 'Settlement' | 'Bank Credit';

interface ChainNode {
  type: NodeType;
  status: NodeStatus;
  document: string | null;
  fields: Record<string, string>;
  observation: string;
}

interface TransactionChain {
  id: string;
  platform: string;
  amount: number;
  date: string;
  overallStatus: 'Complete' | 'Action Needed';
  nodes: ChainNode[];
}

const mockChains: TransactionChain[] = [
  {
    id: 'TRX-99421', platform: 'Zepto', amount: 145000, date: 'Jun 18, 2026', overallStatus: 'Action Needed',
    nodes: [
      { type: 'Purchase Order', status: 'Matched', document: 'PO_ZEP_4911.pdf', fields: { 'PO Number': 'ZEP-4911', 'Amount': '₹1,45,000', 'Items': '24' }, observation: 'Extracted PO details match internal ERP order.' },
      { type: 'Dispatch', status: 'Matched', document: 'Manifest_4911.csv', fields: { 'Waybill': 'AWB-991244', 'Boxes': '4', 'Weight': '24.5kg' }, observation: 'Dispatch weight matches expected PO volumetric weight.' },
      { type: 'GRN', status: 'Conflict', document: 'GRN_ZEP_4911.pdf', fields: { 'Received': '22 Items', 'Missing': '2 Items', 'Value': '₹1,32,000' }, observation: 'GRN indicates 2 missing units of SKU-881. Conflict detected.' },
      { type: 'Invoice', status: 'Partial', document: 'INV_4911.pdf', fields: { 'Inv Amount': '₹1,45,000', 'GST': '18%' }, observation: 'Invoice generated for full PO amount, but GRN shows shortage.' },
      { type: 'Settlement', status: 'Missing', document: null, fields: {}, observation: 'Settlement report not yet generated by Zepto for this cycle.' },
      { type: 'Bank Credit', status: 'Missing', document: null, fields: {}, observation: 'Awaiting settlement.' },
    ]
  },
  {
    id: 'TRX-88210', platform: 'Instamart', amount: 84000, date: 'Jun 15, 2026', overallStatus: 'Complete',
    nodes: [
      { type: 'Purchase Order', status: 'Matched', document: 'PO_INS_882.pdf', fields: { 'Amount': '₹84,000' }, observation: 'Matched perfectly.' },
      { type: 'Dispatch', status: 'Matched', document: 'Manifest_882.csv', fields: { 'Status': 'Delivered' }, observation: 'Verified.' },
      { type: 'GRN', status: 'Matched', document: 'GRN_INS_882.pdf', fields: { 'Amount': '₹84,000' }, observation: 'All items received.' },
      { type: 'Invoice', status: 'Matched', document: 'INV_882.pdf', fields: { 'Amount': '₹84,000' }, observation: 'Matches GRN.' },
      { type: 'Settlement', status: 'Matched', document: 'SET_INS_Jun15.xml', fields: { 'Settled': '₹82,320', 'Commission': '₹1,680' }, observation: 'Commission rate 2% matches contract.' },
      { type: 'Bank Credit', status: 'Matched', document: 'HDFC_Stmt_Jun.csv', fields: { 'Credit': '₹82,320', 'Ref': 'UTR-99129481' }, observation: 'Bank line item reconciled.' },
    ]
  },
  {
    id: 'TRX-77319', platform: 'Blinkit', amount: 210000, date: 'Jun 12, 2026', overallStatus: 'Action Needed',
    nodes: [
      { type: 'Purchase Order', status: 'Matched', document: 'PO_BL_773.pdf', fields: { 'Amount': '₹2,10,000' }, observation: 'PO matched.' },
      { type: 'Dispatch', status: 'Matched', document: 'AWB_BL_773.pdf', fields: { 'Weight': '45kg' }, observation: 'Dispatch confirmed.' },
      { type: 'GRN', status: 'Matched', document: 'GRN_BL_773.pdf', fields: { 'Received': 'Full' }, observation: '100% fill rate.' },
      { type: 'Invoice', status: 'Matched', document: 'INV_773.pdf', fields: { 'Amount': '₹2,10,000' }, observation: 'Invoice verified.' },
      { type: 'Settlement', status: 'Conflict', document: 'SET_BL_Jun12.csv', fields: { 'Settled': '₹1,85,000', 'Deduction': '₹25,000' }, observation: `Platform deducted ₹25,000.
Claimed reason: Logistics SLA breach.
Evidence searched:
• No delayed dispatch found (AWB scanned on time).
• No logistics penalty clause in contract amendment.
Historical average penalty for this platform is 0.1%.
Current deduction equals 11.9%.
Confidence: 98%.
Recommendation:
Raise dispute immediately.` },
      { type: 'Bank Credit', status: 'Matched', document: 'HDFC_Stmt_Jun.csv', fields: { 'Credit': '₹1,85,000' }, observation: 'Bank amount matches short settlement.' },
    ]
  }
];

const nodeIcons: Record<NodeType, React.ReactNode> = {
  'Purchase Order': <DocIcon />,
  'Dispatch': <DispatchIcon />,
  'GRN': <GRNIcon />,
  'Invoice': <InvoiceIcon />,
  'Settlement': <SettlementIcon />,
  'Bank Credit': <BankIcon />
};

const statusColors: Record<NodeStatus, string> = {
  'Matched': '#10b981',
  'Partial': '#f59e42',
  'Conflict': '#ef4444',
  'Missing': '#9ca3af'
};

const statusIcons: Record<NodeStatus, React.ReactNode> = {
  'Matched': <CheckIcon sx={{ color: '#10b981', fontSize: 20 }} />,
  'Partial': <WarningIcon sx={{ color: '#f59e42', fontSize: 20 }} />,
  'Conflict': <ErrorIcon sx={{ color: '#ef4444', fontSize: 20 }} />,
  'Missing': <MissingIcon sx={{ color: '#9ca3af', fontSize: 20 }} />
};

// --- Component ---

const B2BAccounting: React.FC = () => {
  const [selectedTrx, setSelectedTrx] = useState<TransactionChain>(mockChains[0]);
  const [selectedNode, setSelectedNode] = useState<NodeType | null>('Purchase Order');

  const activeNodeData = useMemo(() => {
    return selectedTrx.nodes.find(n => n.type === selectedNode) || null;
  }, [selectedTrx, selectedNode]);

  return (
    <Box sx={{ p: { xs: 2, md: 4 }, maxWidth: 1400, mx: 'auto', height: '100%' }}>
      {/* Header */}
      <Box sx={{ mb: 4 }}>
        <Typography sx={{ fontWeight: 800, fontSize: 28, letterSpacing: -0.5, color: '#111' }}>
          Evidence Chain
        </Typography>
        <Typography sx={{ fontSize: '0.9rem', color: '#6b7280', mt: 0.5 }}>
          Visual timeline of commercial transactions. No spreadsheets needed.
        </Typography>
      </Box>

      <Grid container spacing={4} sx={{ height: 'calc(100vh - 180px)' }}>
        
        {/* Left Pane: Transaction List */}
        <Grid item xs={12} md={3.5} sx={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
          <Typography sx={{ fontSize: '0.8rem', fontWeight: 700, color: '#9ca3af', textTransform: 'uppercase', mb: 2, letterSpacing: '0.05em' }}>
            Recent Transactions
          </Typography>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, overflowY: 'auto', pr: 1 }}>
            {mockChains.map(trx => (
              <Paper
                key={trx.id}
                onClick={() => { setSelectedTrx(trx); setSelectedNode(trx.nodes[0].type); }}
                sx={{
                  p: 2.5,
                  borderRadius: 3,
                  cursor: 'pointer',
                  border: '1px solid',
                  borderColor: selectedTrx.id === trx.id ? '#6c63ff' : '#e5e7eb',
                  bgcolor: selectedTrx.id === trx.id ? '#f5f3ff' : '#fff',
                  boxShadow: selectedTrx.id === trx.id ? '0 4px 12px rgba(108,99,255,0.1)' : 'none',
                  transition: 'all 0.2s',
                  '&:hover': { borderColor: selectedTrx.id === trx.id ? '#6c63ff' : '#d1d5db' }
                }}
              >
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                  <Typography sx={{ fontWeight: 700, fontSize: '0.95rem', color: '#111' }}>{trx.id}</Typography>
                  <Typography sx={{ fontWeight: 800, fontSize: '1rem', color: '#111' }}>₹{(trx.amount / 100000).toFixed(2)}L</Typography>
                </Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <Typography sx={{ fontSize: '0.8rem', color: '#6b7280' }}>{trx.platform} · {trx.date}</Typography>
                  <Chip 
                    label={trx.overallStatus} 
                    size="small" 
                    sx={{ 
                      fontSize: '0.65rem', fontWeight: 700, height: 20, 
                      bgcolor: trx.overallStatus === 'Complete' ? '#dcfce7' : '#fee2e2',
                      color: trx.overallStatus === 'Complete' ? '#166534' : '#991b1b'
                    }} 
                  />
                </Box>
              </Paper>
            ))}
          </Box>
        </Grid>

        {/* Right Pane: Visual Timeline & Node Details */}
        <Grid item xs={12} md={8.5} sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
          
          <Paper sx={{ p: 4, borderRadius: 4, border: '1px solid #e5e7eb', boxShadow: '0 4px 20px rgba(0,0,0,0.02)', mb: 3, display: 'flex', alignItems: 'center', justifyContent: 'space-between', overflowX: 'auto' }}>
            {selectedTrx.nodes.map((node, i) => (
              <React.Fragment key={node.type}>
                {/* Timeline Node */}
                <Box 
                  onClick={() => setSelectedNode(node.type)}
                  sx={{ 
                    display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1.5, cursor: 'pointer',
                    opacity: node.status === 'Missing' ? 0.6 : 1,
                    transition: 'transform 0.2s',
                    transform: selectedNode === node.type ? 'scale(1.1)' : 'scale(1)',
                  }}
                >
                  <Box sx={{ position: 'relative' }}>
                    <Box 
                      sx={{ 
                        w: 56, h: 56, p: 2, borderRadius: '50%', 
                        bgcolor: selectedNode === node.type ? '#111' : '#f3f4f6', 
                        color: selectedNode === node.type ? '#fff' : '#4b5563',
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        boxShadow: selectedNode === node.type ? '0 8px 16px rgba(0,0,0,0.15)' : 'none',
                        border: '2px solid',
                        borderColor: selectedNode === node.type ? '#111' : 'transparent',
                        transition: 'all 0.2s'
                      }}
                    >
                      {nodeIcons[node.type]}
                    </Box>
                    <Box sx={{ position: 'absolute', bottom: -4, right: -4, bgcolor: '#fff', borderRadius: '50%', p: 0.2 }}>
                      {statusIcons[node.status]}
                    </Box>
                  </Box>
                  <Typography sx={{ fontSize: '0.75rem', fontWeight: 700, color: selectedNode === node.type ? '#111' : '#6b7280', textAlign: 'center', width: 70 }}>
                    {node.type}
                  </Typography>
                </Box>
                
                {/* Connector Line */}
                {i < selectedTrx.nodes.length - 1 && (
                  <Box sx={{ flex: 1, height: 2, bgcolor: node.status === 'Missing' ? '#f3f4f6' : statusColors[node.status], mx: 2, mt: -3, minWidth: 20 }} />
                )}
              </React.Fragment>
            ))}
          </Paper>

          {/* Node Details */}
          {activeNodeData && (
            <Paper sx={{ p: 0, borderRadius: 4, border: '1px solid #e5e7eb', boxShadow: 'none', flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
              
              {/* Node Header */}
              <Box sx={{ p: 3, borderBottom: '1px solid #e5e7eb', bgcolor: '#fafafa', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <Box>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
                    {statusIcons[activeNodeData.status]}
                    <Typography sx={{ fontSize: '1.2rem', fontWeight: 800, color: '#111' }}>
                      {activeNodeData.type} Details
                    </Typography>
                    <Chip 
                      label={activeNodeData.status} 
                      size="small" 
                      sx={{ 
                        fontSize: '0.65rem', fontWeight: 700, height: 20, 
                        bgcolor: activeNodeData.status === 'Matched' ? '#dcfce7' : activeNodeData.status === 'Conflict' ? '#fee2e2' : activeNodeData.status === 'Partial' ? '#ffedd5' : '#f3f4f6',
                        color: statusColors[activeNodeData.status]
                      }} 
                    />
                  </Box>
                  <Typography sx={{ fontSize: '0.85rem', color: '#6b7280' }}>
                    {activeNodeData.document ? `Source: ${activeNodeData.document}` : 'No source document found for this node.'}
                  </Typography>
                </Box>
                {activeNodeData.document && (
                  <Button variant="outlined" size="small" startIcon={<DownloadIcon />} sx={{ borderColor: '#d1d5db', color: '#374151', textTransform: 'none', fontWeight: 600, borderRadius: 2 }}>
                    View Original
                  </Button>
                )}
              </Box>

              {/* Node Content */}
              <Box sx={{ p: 4, flex: 1, overflowY: 'auto' }}>
                
                {/* AI Observation */}
                <Paper sx={{ p: 2.5, mb: 4, borderRadius: 3, border: '1px solid', borderColor: activeNodeData.status === 'Conflict' ? '#fecaca' : '#e9d5ff', bgcolor: activeNodeData.status === 'Conflict' ? '#fef2f2' : '#faf5ff', boxShadow: 'none' }}>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1.5 }}>
                    <AIIcon sx={{ fontSize: 18, color: activeNodeData.status === 'Conflict' ? '#ef4444' : '#7c3aed' }} />
                    <Typography sx={{ fontSize: '0.8rem', fontWeight: 800, color: activeNodeData.status === 'Conflict' ? '#991b1b' : '#6b21a8', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                      AI Observation
                    </Typography>
                  </Box>
                  <Typography sx={{ fontSize: '0.95rem', color: activeNodeData.status === 'Conflict' ? '#7f1d1d' : '#4c1d95', lineHeight: 1.6, fontWeight: 500, whiteSpace: 'pre-line' }}>
                    {activeNodeData.observation}
                  </Typography>
                </Paper>

                {/* Extracted Fields */}
                <Typography sx={{ fontSize: '0.85rem', fontWeight: 700, color: '#9ca3af', textTransform: 'uppercase', letterSpacing: '0.05em', mb: 2 }}>
                  Extracted Fields
                </Typography>
                
                {Object.keys(activeNodeData.fields).length > 0 ? (
                  <Grid container spacing={2}>
                    {Object.entries(activeNodeData.fields).map(([key, val]) => (
                      <Grid item xs={12} sm={6} md={4} key={key}>
                        <Paper sx={{ p: 2, borderRadius: 3, border: '1px solid #f3f4f6', bgcolor: '#fff', boxShadow: '0 2px 8px rgba(0,0,0,0.02)' }}>
                          <Typography sx={{ fontSize: '0.75rem', color: '#6b7280', mb: 0.5 }}>{key}</Typography>
                          <Typography sx={{ fontSize: '1rem', fontWeight: 700, color: '#111' }}>{val}</Typography>
                        </Paper>
                      </Grid>
                    ))}
                  </Grid>
                ) : (
                  <Typography sx={{ fontSize: '0.9rem', color: '#9ca3af', fontStyle: 'italic' }}>
                    No fields extracted. Document is missing or processing.
                  </Typography>
                )}

              </Box>
            </Paper>
          )}

        </Grid>
      </Grid>
    </Box>
  );
};

export default B2BAccounting;
