// Shared types for the B2B (Nexbit) mock-data layer - Cosmix demo.
// Frontend-only fixtures - no backend, no fetch. All amounts in whole rupees.

export type ChannelName = 'Blinkit' | 'Zepto' | 'Reliance' | 'Cafes – Bangalore' | 'Amazon' | 'Reliance Retail' | 'Third Wave Coffee' | 'Blue Tokai Coffee' | 'Subko Coffee' | 'Starbucks' | 'Hatti Kaapi';

export interface Channel {
  name: ChannelName;
  /** Marketplace / channel settlement model, shown as context only. */
  model: string;
  connected: boolean;
}

export interface Sku {
  id: string;
  product: string;
  variant: string;
  /** Display name, e.g. "Plant Protein - 250g". */
  label: string;
}

/** Canonical, cross-footed headline numbers. Later views reference these - never redefine. */
export interface HeadlineMetric {
  key: string;
  label: string;
  /** Raw value in rupees (or percent for ratio metrics). */
  value: number;
  /** Pre-formatted display string matching the design spec. */
  display: string;
  unit: 'inr' | 'percent';
}

export interface ChannelPerformance {
  channel: ChannelName;
  /** Gross invoice value raised to the channel. */
  invoiceRaised: number;
  /** PO value generated by the channel (same as invoiceRaised in current data). */
  poGenerated: number;
  /** Net expected payout after legitimate deductions. */
  expectedPayout: number;
  /** Actual amount received / deposited in bank. */
  received: number;
  /** Expected payout minus received — money still owed. */
  unsettled: number;
  /** Deductions identified as wrong based on contract comparison. */
  wrongDeductions: number;
  /** Legacy alias — kept for downstream compatibility. */
  expected: number; 
  /** Legacy alias — kept for downstream compatibility. */
  unresolved: number; 
  netRealisationPct: number;
}

export type IssueType =
  | 'Pending GRN'
  | 'Short payment'
  | 'Debit note – damages'
  | 'Debit note – returns'
  | 'Visibility fee duplicate'
  | 'Invoice missing'
  | 'Settlement pending'
  | 'Rate variance'
  | 'Overdue'
  | 'Commission discrepancy'
  | 'Storage overcharge';

export type Confidence = 'High' | 'Med' | 'Low';

export interface FlaggedIssue {
  id: string;
  channel: ChannelName;
  title: string;
  detail: string;
  amount: number;
  type: IssueType;
  confidence: Confidence;
  status?: string; 
  daysOpen?: number;
  urgency?: string;
}

export type GRNStatus = 'Accepted' | 'Pending' | 'Partial' | 'Missing';
export type ReconStatus = 'Matched' | 'Pending GRN' | 'Short paid' | 'Over-deducted' | 'Disputed' | 'Missing invoice';

export interface VariancePart {
  label: string;
  /** Signed rupee effect on payout. Negative = reduced payout (underpayment). */
  amount: number;
  /** Plain-language reason this component arose. */
  why: string;
}

/** Three-way matching status for a reconciliation line item. */
export interface ThreeWayMatch {
  po: { ref: string; status: 'Matched' | 'Pending' | 'Missing' | 'Disputed'; amount: number };
  grn: { ref: string; status: 'Matched' | 'Pending' | 'Missing' | 'Disputed'; amount: number; unitsAccepted: number; unitsOrdered: number };
  invoice: { ref: string; status: 'Matched' | 'Pending' | 'Missing' | 'Disputed'; amount: number };
}

// ── Action Timeline / Action Centre types ──────────────────────────────────────
export type DisputeStatus = 'Detected' | 'Reviewed' | 'Dispute initiated' | 'Follow-up' | 'Resolved';

export interface IssueAction {
  date: string;
  action: string;
  status: 'Sent' | 'Pending' | 'Scheduled' | 'Resolved' | 'Detected' | 'Reviewed' | 'Dispute raised' | 'Evidence requested';
}

export interface ActionItem {
  id: string;
  issue: string;
  channel: ChannelName;
  amount: number;
  status: DisputeStatus | 'Dispute ready' | 'Follow-up sent';
  daysOpen: number;
  urgency: string; 
  history: IssueAction[];
  nextAction?: string;
  relatedRef?: string;
}

export interface ChannelPosition {
  channel: ChannelName;
  expected: number;
  received: number;
  unresolved: number;
  issues: ActionItem[];
}

export interface DisputePipeline {
  detected: number;
  reviewed: number;
  disputed: number;
  followUp: number;
  resolved: number;
}

export type NudgeType = '7-day' | '15-day' | 'Dispute' | 'Escalation';
export type NudgeStatus = 'Sent' | 'Pending' | 'Scheduled';

export interface FollowUpNudge {
  id: string;
  channel: ChannelName;
  relatedIssue: string;
  nudgeType: NudgeType;
  message: string;
  status: NudgeStatus;
  date: string;
}

// ── Rate card & contract types ───────────────────────────────────────────────
export interface RateCardLine {
  code: string;
  label: string;
  /** Contracted basis / value, e.g. "16% of GMV" or "₹18 / order". */
  contracted: string;
  authorised: boolean;
  /** Short note for an unauthorised line, e.g. "no signed basis". */
  note?: string;
}

export interface ChannelContract {
  channel: ChannelName;
  model: string;
  contractRef: string;
  effective: string;
  source: string;
  rateCard: RateCardLine[];
}

export type DiscountType = 'percent' | 'perUnit';
export type DiscountStatus = 'Active' | 'Scheduled' | 'Ended';

export interface SecondaryDiscount {
  id: string;
  channel: ChannelName;
  name: string;
  skuIds: string[];
  discountType: DiscountType;
  discountValue: number;
  brandFundedPct: number;
  startDate: string;
  endDate: string;
  unitsInWindow: number;
  avgSellingPrice: number;
}

// ── Channel drilldown types ─────────────────────────────────────────────────
export interface DeductionBreakdownLine {
  label: string;
  contracted: string;
  actual: number;
  expected: number;
  variance: number;
}

export interface ChannelDrilldownData {
  channel: ChannelName;
  model: string;
  contractRef: string;
  payoutLogic: string;
  salesInPeriod: number;
  grossDeductions: number;
  expectedReceivable: number;
  receivedAmount: number;
  pendingBalance: number;
  deductionBreakdown: DeductionBreakdownLine[];
  issueFlags: { type: IssueType; count: number; amount: number }[];
  upcomingPayouts: { date: string; amount: number; status: 'Expected' | 'Overdue' | 'Partial' }[];
  accounts?: {
    name: string;
    salesInPeriod: number;
    receivedAmount: number;
    pendingBalance: number;
    status: 'Settled' | 'Overdue' | 'Partial' | 'Pending';
  }[];
}

// Monthly trend data point
export interface TrendDataPoint {
  month: string;
  expectedLakhs: number;
  receivedLakhs: number;
  gapLakhs: number;
}

export interface UpcomingPayout {
  channel: string;
  date: string;
  amount: number;
  status: 'Expected' | 'Overdue' | 'Partial';
}
